skip ppc64le builds due to missing upstreams
conda-forge/r-terra-feedstock pull request #88
Opened 2024-05-21 14:20 UTC by akrherz

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
*  Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

The ppc64le arch is now getting skipped by upstreams like https://github.com/conda-forge/gdal-feedstock/issues/918 , so it needs to be skipped here too...

@conda-forge-admin please rerender

2024-05-21 14:22 UTC, akrherz commented
@conda-forge-admin please rerender

2024-05-21 19:17 UTC, mfansler requested changes

2024-05-21 19:17 UTC, mfansler commented on recipe/meta.yaml
>    skip: true  # [win]
I believe you wanted:

```suggestion
  merge_build_host: true  # [win]
  skip: true  # [win or ppc64le]
```

2024-05-21 19:20 UTC, akrherz commented
@conda-forge-admin please rerender

2024-05-21 19:20 UTC, akrherz commented on recipe/meta.yaml
>    skip: true  # [win]
ooopsy :(  Thank you.

2024-05-21 20:19 UTC, mfansler approved these changes
Thanks for submitting these! :heart:

2024-05-21 20:20 UTC, merged

2025-02-22 06:59 UTC, davised commented
Looks like the upstreams re-enabled ppc64le.

- https://github.com/conda-forge/gdal-feedstock/pull/968

I'd fiddle with doing a PR for this but I've not managed conda-forge feedstocks before. I was able to re-build locally on ppc64le with the recipe after conversion to rattler-build, so I think that's a success.